#! /usr/bin/env node
const { SiteImporter } = require("./SiteImporter.js")
const path = require("path")

const cases = `http://www.aaronsw.com
https://5f5.org
https://aaronsw.com
https://ai.stanford.edu
https://alexharri.com
https://alexshroyer.com
https://amirhirsch.com
https://amygoodchild.com
https://andrewchen.com
https://anniecherkaev.com
https://anselmlevskaya.com
https://arno.org
https://aseemk.substack.com
https://asimovinstitute.org
https://astralcodexten.com
https://astrobiology.com
https://balupton.com
https://believermag.com
https://blog.gingerbeardman.com
https://blog.jeremyrwelch.com
https://blog.jim-nielsen.com
https://blog.mollywhite.net
https://blog.oquijano.net
https://blog.rongarret.info
https://blog.samaltman.com
https://blog.vrypan.net
https://blog.wilsonl.in
https://blogmaverick.com
https://breckyunits.com
https://brettjonesdev.com
https://briefer.cloud
https://burn-heart.com
https://calmfund.com
https://calnewport.com
https://casnocha.com
https://centauri-dreams.org
https://chelseatroy.com
https://ciechanow.ski
https://codelab.farai.xyz
https://conduition.io
https://cryptocode.github.io
https://dangrover.com
https://danilafe.com
https://danromero.org
https://daringfireball.net
https://daytoninmanhattan.blogspot.com
https://devever.net
https://dgerrells.com
https://distill.pub
https://dumbph.com
https://educatingsilicon.com
https://elopezr.com
https://elusivewordsmith.com
https://erikdemaine.org
https://escapethealgorithm.substack.com
https://evjang.com
https://exple.tive.org
https://fasterthanli.me
https://filfre.net
https://forrestbrazeal.com
https://fredrikbk.com
https://fs.blog
https://gpanders.com
https://graphite.dev
https://graydon2.dreamwidth.org
https://gurwinder.blog
https://hanselman.com
https://herman.bearblog.dev
https://heyman.info
https://hudzah.com
https://idlewords.com
https://idvork.in
https://jackkelly.name
https://jasoncrawford.org
https://jeena.net
https://jemarch.net
https://jillianhess.substack.com
https://johnhorgan.org
https://journal.stuffwithstuff.com
https://juliagalef.com
https://karpathy.github.io
https://kayode.co
https://konstantinschubert.com
https://laurent.le-brun.eu
https://lrb.co.uk
https://ma.tt
https://maggieappleton.com
https://marginalrevolution.com
https://mathematicaforprediction.wordpress.com
https://mattcutts.com
https://matthewstrom.com
https://mattkeeter.com
https://mbuffett.com
https://mcsweeneys.net
https://meyerweb.com
https://mikeknoop.com
https://mk.bcgsc.ca
https://morethanone.info
https://nonint.com
https://norvig.com
https://nsl.com
https://oranlooney.com
https://parkerhiggins.net
https://patrickcollison.com
https://paulgraham.com
https://philmohun.com
https://pointersgonewild.com
https://rachelbythebay.com
https://razetime.github.io
https://redwoodresearch.substack.com
https://rjlipton.com
https://rongarret.info
https://rubenerd.com
https://science.org
https://scottaaronson.blog
https://seths.blog
https://sillycross.github.io
https://sive.rs
https://slatestarcodex.com
https://smallweb.page
https://social-protocols.org
https://sparktoro.com
https://stefantheard.com
https://stephentemplin.com
https://steveruiz.me
https://suhailkakar.com
https://swtch.com
https://terrytao.wordpress.com
https://thechipletter.substack.com
https://theluddite.org
https://thenumb.at
https://thesephist.com
https://theunderground.blog
https://timdbg.com
https://tjw.io
https://tom.preston-werner.com
https://torrentfreak.com
https://tratt.net
https://vedgie.net
https://vexlio.com
https://vickiboykis.com
https://vitalik.ca
https://vlmantova.github.io
https://waitbutwhy.com
https://westurner.github.io
https://worksinprogress.co
https://worrydream.com
https://writings.stephenwolfram.com
https://xania.org
https://xkcd.com
`.split("\n")

const rootFolder = path.join(__dirname, "sites")
cases.forEach(async url => new SiteImporter().importFromUrl(url, rootFolder))
